Dev harish
HarishOjhaCCTECH/CNCToolPathGenerator pull request #5
Opened 2024-05-10 11:41 UTC by HarishOjhaCCTECH

Code status:
![image](https://github.com/HarishOjhaCCTECH/CNCToolPathGenerator/assets/158055492/1134abe8-fff4-4665-9956-370ab09f2559)

2024-05-10 12:13 UTC, HarishOjhaCCTECH commented
below is the wide screenshot of error list:
![image](https://github.com/HarishOjhaCCTECH/CNCToolPathGenerator/assets/158055492/9e824ce8-1654-4111-a21d-cc9dbeb0f4ae)

2024-05-12 12:26 UTC, vinayaksutar commented on Model/Cube.stl
remove if not required

2024-05-12 12:26 UTC, vinayaksutar commented on Model/Cylinder.cpp
remove if not required

2024-05-12 12:26 UTC, vinayaksutar commented on Model/Cylinder.cpp
Correct the file name

2024-05-12 12:27 UTC, vinayaksutar commented on Model/Cylinder.h
Correct the file name

2024-05-12 12:27 UTC, vinayaksutar commented on Model/DataStorage.cpp
Correct the file name

2024-05-12 12:28 UTC, vinayaksutar commented on Model/DataStorage.h
Correct the file name

2024-05-12 12:28 UTC, vinayaksutar commented on Model/ToolPath.cpp
simplify the code

2024-05-12 12:29 UTC, vinayaksutar commented on Model/ToolPath.h
Correct the function names.

2024-05-12 12:30 UTC, vinayaksutar requested changes
1. Code cleanup
2. Verify the file and function names
3. Add logical comments

2024-05-12 17:07 UTC, HarishOjhaCCTECH commented on Model/Cube.stl
It is required, as it one of the options for choose stl

2024-05-12 17:08 UTC, HarishOjhaCCTECH commented on Model/Cylinder.cpp
Changed it to ToolCylinder because the whole purpose of this shape is to calculate the tool's vertices.

2024-05-12 17:08 UTC, HarishOjhaCCTECH commented on Model/Cylinder.h
Done

2024-05-12 17:09 UTC, HarishOjhaCCTECH commented on Model/DataStorage.cpp
Convert the DataStorage to DataManager class because it is handling and processing all the data

2024-05-12 17:09 UTC, HarishOjhaCCTECH commented on Model/DataStorage.h
Done

2024-05-16 07:11 UTC, HarishOjhaCCTECH commented
Lots of faulty code due to wrong understanding of concepts

2024-05-16 07:11 UTC, closed without merging